### ISSUE TITLE
The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by simonbcn** [AyatanaIndicators/ayatana-webmail#1]
```
Operating System: Arch Linux
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.1-zen1-1-zen
OS Type: 64-bit
```
Installed from AUR package: [`ayatana-webmail`](https://aur.archlinux.org/packages/ayatana-webmail/)
It doesn't autostart and when I execute `ayatana-webmail` in console, it shows the error: 
```
2020-08-18 19:19:54,203: Ayatana Webmail: CRITICAL: The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by ghost** [comment]
@simonbcn 

You need something that provides org.freedesktop.secrets. Other desktop environments use **gnome-keyring** for that. I'm a bit surprised that KDE does not have a secret storage mechanism out-of-the-box. As an alternative, you could try gnome-keyring (it should not pull any gnome stuff).

Could you please report back so I could add the proper dependency for KDE people? Thanks.

Also, ayatana-indicator-messages needs to be 0.8 if you plan to use that as well. @sunweaver is in octopus-mode, rolling out new versions of everything all over the place, but the versions may be out-of-sync for the next day, maybe less.

**Comment by ghost** [comment]
@simonbcn

The AUR package now depends on gnome-keyring, which should solve the problem. ayatana-indicator-messages has also been updated to 0.8.0. I think KDE users can consider ayatana-indicator-messages optional and edit it out if they wish.

Could you please reinstall ayatana-webmail and report back so I could know whether to close this. Thank you.

**Comment by ghost** [comment]
I am closing this as the issue refers to an old version Ayatana Webmail.
