### ISSUE TITLE
weblate integration

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-webmail#10]
@tari01: I have added this project to hosted Weblate now:
https://hosted.weblate.org/projects/ayatana-indicators/ayatana-webmail/

As you already mentioned earlier, it has 3 .po file locations. We need to / should merge those into one (po/*.po).

I can look at that later (the coming week), if needed. Let me know (and assign me).

**Comment by ghost** [comment]
Do you know if Weblate works with prefixed *.po files? (po/app_de.po, po/desktop_de.po)? That would solve it easily.

**Comment by ghost** [comment]
The po/*.po filemask suggests it should.

**Comment by sunweaver** [comment]
> Do you know if Weblate works with prefixed *.po files? (po/app_de.po, po/desktop_de.po)? That would solve it easily.

Yes, it does. But we should rather move all translations into a single file. That is the absolutely preferred approach here IMHO.

**Comment by ghost** [comment]
Resolved by https://github.com/AyatanaIndicators/ayatana-webmail/commit/54f82d46f7f1449b97600fdc33a18184489a1a2e
