### ISSUE TITLE
Bizarre login error

### ISSUE THREAD

**Issue by SuchComputers** [AyatanaIndicators/ayatana-webmail#30]
While using Ayatana webmail (for Gmail) on Ubuntu 20.04 the following error occurs (circa from 1st June 2022):
„Connection failure
Failed to connect to mail account. The returned error was:
‘[AUTHENTICATIONFAILED] Invalid credentials (Failure)’ ”

The thing is that the credentials are valid. I have checked this by writing the credentials in a text file and then copy-pasting them into: 
a) web-browser login page = the results were correct. 
b) into Ayatana webmail and getting the mentioned error.

Any ideas what is going on? And how to fix this?
P.S. Sorry for non-timely responding caused by my Ayatana Webmail problem :)

**Comment by ghost** [comment]
@SuchComputers 

Google no longer supports accessing your account with your username/password. You need to enable 2-factor authentication and generate an application password for Ayatana Webmail.

You can run `ayatana-webmail-reset` to make the application forget your account, restart it, then re-enter your credentials.

Please close this if your issue is solved. I'm also here if you need further help.

**Comment by SuchComputers** [comment]
Thank You very much, the advice worked like a charm.
To elaborate for people with similar problem:
A) Why this error occurs: „from May 30, 2022, Google no longer supports the use of third-party apps or devices”. Aka „Less secure apps and Google account” see: https://support.google.com/accounts/answer/6010255
B) The solution – first enable the two step verification and then give your chosen app rights to login.
1) Enable two-step verification.
Sign in into Gmail account and select your profile picture or icon → Select „Manage (Your) Google Account” → (a new tab opens) In the left pane, select „Security” → Under „Signing in to Google”, select „2-Step Verification” (it is marked as „turned off”) → Select „Get Started” → Enter your password and select „Next” → Enter your mobile device's number, select „Text message”, then select „Next” → Google will send you the text message. Select „Turn On” to turn on two-factor authentication. Now you'll be prompted to use your second step each time you log on to Gmail. (This can be changed on your phone if you choose one of the 3 suggested methods).
2) logging in with passwords into applications (enabling chosen application to login with a unique one-time-entered-password): 
https://support.google.com/accounts/answer/185833?hl=en
