### ISSUE TITLE
failed to connect to mail account. the returned error was:`[AUTHENTICATIONFAILED] invalid credentials (failure)`

### ISSUE THREAD

**Issue by sevo1984** [AyatanaIndicators/ayatana-webmail#31]
Hi there,

I am just an ordinary user, and I've been using Unity-Mail and then Ayatana Webmail for quite some time. Recently I upgraded to Ubuntu 22.04 on two computers, but Ayatana-Webmail keeps sending me the following connection error:

failed to connect to mail account. the returned error was:`[AUTHENTICATIONFAILED] invalid credentials (failure)`

The credentials I am using are valid, and after some search, the error appears to be related to Google, where access to less secure apps is disabled and I cannot turn it on any more.

Am I doing something wrong? Is it possible to get Ayatana-webmail working on my gmail account?

Kind regards and thank you for your great work,
![Screenshot from 2022-06-13 19-05-29](https://user-images.githubusercontent.com/2257560/173409773-9eaab861-fa75-48d2-9e6f-90471d3f04d7.png)

Goran

**Comment by ghost** [comment]
@sevo1984 

Please see https://github.com/AyatanaIndicators/ayatana-webmail/issues/30#issuecomment-1152904225 for a solution. I am closing this as a duplicate.

**Comment by sevo1984** [comment]
Thank you sooooo much for a quick reply!!!
Cheers, G
