### ISSUE TITLE
Ship several configuration templates for different Webmailers

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-webmail#4]
I'd love to get the Horde Webmailer fully integrated into Ayatana Webmail. However, I'd have to fiddle around with all the URLs to invoke certain webmail dialogs (this is a feature, I really like about Ayatana Webmail).

Could it be an option to add a profile template selector for the various webmailers out there? (e.g. Roundcube, Horde Webmail, also commercial services like GMail, etc.).

**Comment by sunweaver** [comment]
@sunweaver is talking about the settings dialog window and the correct URLs required to address certain features in the webmailers (open INBOX, open sent folder, compose new message, etc.).

**Comment by ghost** [comment]
> @sunweaver is talking about the settings dialog window and the correct URLs required to address certain features in the webmailers (open INBOX, open sent folder, compose new message, etc.).

@tari01 understands, he runs his own Roundcube

**Comment by ghost** [comment]
Let this be a place where we collect the data for this, like so:

NAME: Example Mail
PORT: 993
HOME: https://mail.example.com/home/
COMPOSE: https://mail.example.com/compose/
INBOX: https://mail.example.com/inbox/
INBOX PARAM: A string including **$MSG_UID**
SENT: https://mail.example.com/sent/

**Comment by ghost** [comment]
Resolved by https://github.com/AyatanaIndicators/ayatana-webmail/commit/ef27a57e0d507c5be37b0e065b5a729670552bdb

Now we need to get more templates and feed them into the gschema.
