### ISSUE TITLE
gnome-keyring dialog freezes the whole panel (in MATE)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-webmail#5]
If Ayatana Webmail triggeres the GNOME keyring passphrase dialog (to unlock the keyring), the complete mate-panel is blocked and in accessible. This should not be. In my case, I need to open a terminal, run ``setxkbmap de`` in that terminal and only then can enter my password properly (without thinking to much about where to put my fingers). With this panel freeze, I can not really access a terminal window launcher in the application menu.

**Comment by ghost** [comment]
Confirmed, but this is not an Ayatana Webmail issue. Tested with other applications trying to access the keyring (with Ayatana Webmail not running). Gnome Keyring is in total blocking mode when it presents its dialog. The bug report should go there.

Closing this as invalid.
