### ISSUE TITLE
folder list too small

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-webmail#7]
On my system, when starting the settings dialog, I only see two folders in the selection list. Note, that my email box is considerably large (more than 100 folders). It would be handy if one could at least see 5-8 lines of folders. I know that I can enlarge the folder list via dragging on its corner, but still... Just a suggestion to show more lines by default here (without making the dialog window too big).

**Comment by ghost** [comment]
Resolved by https://github.com/AyatanaIndicators/ayatana-webmail/commit/ef27a57e0d507c5be37b0e065b5a729670552bdb
